#To be used for In-Memory DB:

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#############################################################

#My SQL DB:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-spring-security
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: always
    hikari:
      maximum-pool-size: 5       # Maximum number of connections in the pool
      minimum-idle: 2             # Minimum number of idle connections in the pool
      idle-timeout: 10000        # Connection idle timeout in milliseconds (5 minutes)
      max-lifetime: 1800000       # Maximum lifetime of a connection in milliseconds (30 minutes)
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#############################################################

logging:
  level:
    org.springframework: INFO